apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: rabbitmq-consumer-network-delay
  namespace: chaos-testing
spec:
  action: delay
  mode: fixed-percent
  value: "30"
  selector:
    namespaces:
      - rabbitmq
    labelSelectors:
      app: rabbitmq-consumer
  duration: "5m"
  scheduler:
    cron: "@every 20m"
  networkDelay:
    latency: "500ms"
    correlation: "100"
    jitter: "100ms"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: rabbitmq-consumer-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: fixed-percent
  value: "50"
  selector:
    namespaces:
      - rabbitmq
    labelSelectors:
      app: rabbitmq-consumer
  duration: "2m"
  scheduler:
    cron: "@every 15m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: rabbitmq-cpu-stress
  namespace: chaos-testing
spec:
  mode: fixed-percent
  value: "40"
  selector:
    namespaces:
      - rabbitmq
    labelSelectors:
      app: rabbitmq-consumer
  stressors:
    cpu:
      workers: 4
      load: 90
  duration: "3m"
  scheduler:
    cron: "@every 25m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: rabbitmq-disk-io-stress
  namespace: chaos-testing
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - rabbitmq
    labelSelectors:
      app: rabbitmq-server
  duration: "4m"
  scheduler:
    cron: "@every 30m"
  ioFault:
    errno: 28
    weight: 100
  path: "/var/lib/rabbitmq"
  percent: 100
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: rabbitmq-memory-pressure
  namespace: chaos-testing
spec:
  action: loss
  mode: fixed-percent
  value: "20"
  selector:
    namespaces:
      - rabbitmq
    labelSelectors:
      app: rabbitmq-server
  duration: "3m"
  scheduler:
    cron: "@every 18m"
  networkLoss:
    loss: "20"
    correlation: "100" 